package com.ztesoft.zsmart.nros.crm.core.client.model.dto;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;

/**
 * 事件触发记录DTO
 * @author fan.chaolin
 * @date 2019/4/19
 */
@Data
public class EventTriggerHistoryDTO extends BaseModel implements Serializable {

    /**
     * 事件触发记录-商家ID
     */
    private Long merchantId;

    /**
     * 事件触发记录-事件ID
     */
    private Long eventId;

    /**
     * 事件触发记录-触发会员ID
     */
    private Long memberId;

    /**
     * 事件触发记录-会员名称
     */
    private String memberName;

    /**
     * 事件触发记录-手机号
     */
    private String memberPhone;

    /**
     * 事件触发记录-微信昵称
     */
    private String wxNickname;

    /**
     * 事件触发记录-流程执行是否完成
     */
    private String isProcessFinished;

    /**
     * 事件触发记录-营销流程定义ID
     */
    private Long marketingId;

    /**
     * 事件触发记录-触发识别ID
     */
    private Long identifyId;

    /**
     * 事件触发记录-触发识别编码
     */
    private String identifyCode;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
