package com.ztesoft.zsmart.nros.crm.core.client.model.dto;

import java.io.Serializable;

import com.ztesoft.zsmart.nros.common.model.BaseModel;

import lombok.Data;

/**
 * 营销流程实例DTO
 * 
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-07-24
 */
@Data
public class MarketingInstanceDTO extends BaseModel implements Serializable {
    /**
     * 流程定义ID
     */
    private Long marketingId;

    /**
     * 流程实例ID
     */
    private String marketingInstanceId;

    /**
     * 流程执行目标用户数
     */
    private Long targetUserCount;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}