package com.ztesoft.zsmart.nros.crm.core.client.model.dto;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * 营销定义DTO
 * @author   wangzhe
 * @date     2019/4/17 16:38
 */
@Data
public class MarketingDefineDTO extends BaseModel implements Serializable {

    /**
     * 营销流程定义-模板ID
     */
    private Long templateId;

    /**
     * 营销流程定义-营销流程名称
     */
    private String marketingName;

    /**
     * 营销流程定义-营销流程备注
     */
    private String marketingRemark;

    /**
     * 营销流程定义-订单分析起始
     */
    private Date analysisStart;

    /**
     * 营销流程定义-订单分析结束
     */
    private Date analysisEnd;

    /**
     * 营销流程定义-是否相对日期:[0]否,[1]是
     */
    private String isRelative;

    /**
     * 营销流程定义-向前推移天数
     */
    private Integer beforeCount;

    /**
     * 营销流程定义-向后推移天数
     */
    private Integer afterCount;

    /**
     * 营销流程定义-营销类型:[1]主动营销,[2]事件营销
     */
    private String marketingType;

    /**
     * 营销流程定义-营销配置json信息
     */
    private String marketingConfigJson;

    /**
     * 营销流程定义-流程执行配置json信息
     */
    private String excuteConfigJson;

    /**
     * 营销流程定义-是否永久有效:[0]否,[1]是
     */
    private String isAlwaysValid;

    /**
     * 营销流程定义-开始时间
     */
    private Date starttime;

    /**
     * 营销流程定义-结束时间
     */
    private Date finishtime;

    /**
     * 营销流程定义-触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     */
    private String frequenceType;

    /**
     * 营销流程定义-频次数量
     */
    private Integer frequenceCount;

    /**
     * 营销流程定义-频次单位
     */
    private String frequenceUnit;

    /**
     * 营销流程定义-营销流程状态:[0]设计中,[1]生效,[2]失效
     */
    private String marketingStatus;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}