package com.ztesoft.zsmart.nros.crm.core.client.model.dto;

import java.io.Serializable;

import com.ztesoft.zsmart.nros.common.model.BaseModel;

import lombok.Data;

/**
 * 营销流程实例分析明细DTO
 * 
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-07-24
 */
@Data
public class MarketingInstanceStaticsDetailDTO extends BaseModel implements Serializable {
    /**
     * 流程节点ID
     */
    private String nodeId;

    /**
     * 流程节点名称
     */
    private String nodeName;

    /**
     * 流程节点目标用户数
     */
    private Long targetUserCount;

    /**
     * 流程节点目标动作统计
     */
    private Long targetActionCount;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}