package com.ztesoft.zsmart.nros.crm.core.server.domain.smstemplate.model;


import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;

/**
 * @ClassName SmsTemplateBO
 * @Description
 * @Author will_lee
 * @Date 2019/6/12 11:26
 **/
@Data
public class SmsTemplateBO extends BaseModel implements Serializable {

    /**
     * 短信模板表-短信模板名称
     */
    private String templateName;

    /**
     * 短信模板表-短信模板内容
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
