package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 营销活动服务明细
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-18
 */
public class CampaignServiceDO extends BaseModel implements Serializable {
    /**
     * 营销活动服务明细-邀请人手机
     */
    private String invitorPhone;

    /**
     * 营销活动服务明细-注册人手机
     */
    private String registerPhone;

    /**
     * 营销活动服务明细-报名人手机
     */
    private String signPhone;

    /**
     * 营销活动服务明细-预约门店ID
     */
    private Long reservationStoreId;

    /**
     * 营销活动服务明细-是否新用户
     */
    private String isNew;

    /**
     * 营销活动服务明细-审核状态 0. 审核通过 1. 审核拒绝  2.取消预约
     */
    private String auditStatus;

    /**
     * 营销活动服务明细-是否已经签到
     */
    private String isSignIn;

    /**
     * 营销活动服务明细-签到码
     */
    private String signInCode;

    /**
     * 营销活动服务明细-签到时间
     */
    private String signInTime;

    /**
     * 营销活动服务明细-报名时间
     */
    private String signTime;

    /**
     * 营销活动服务明细-注册时间
     */
    private Date registerTime;

    /**
     * 营销活动服务明细-奖励发放
     */
    private String isReward;

    /**
     * 营销活动服务明细-预约时间段id
     */
    private Long reserveTimeId;

    /**
     * 营销活动服务明细-活动ID
     */
    private Long campaignId;

    /**
     * 营销活动服务明细-签到用户姓名
     */
    private String signName;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：营销活动服务明细-邀请人手机
     *
     * @return 邀请人手机
     */
    public String getInvitorPhone() {
        return invitorPhone;
    }

    /**
     * 设置：营销活动服务明细-邀请人手机
     *
     * @param invitorPhone 营销活动服务明细-邀请人手机
     */
    public void setInvitorPhone(String invitorPhone) {
        this.invitorPhone = invitorPhone == null ? null : invitorPhone.trim();
    }

    /**
     * 获取：营销活动服务明细-注册人手机
     *
     * @return 注册人手机
     */
    public String getRegisterPhone() {
        return registerPhone;
    }

    /**
     * 设置：营销活动服务明细-注册人手机
     *
     * @param registerPhone 营销活动服务明细-注册人手机
     */
    public void setRegisterPhone(String registerPhone) {
        this.registerPhone = registerPhone == null ? null : registerPhone.trim();
    }

    /**
     * 获取：营销活动服务明细-报名人手机
     *
     * @return 报名人手机
     */
    public String getSignPhone() {
        return signPhone;
    }

    /**
     * 设置：营销活动服务明细-报名人手机
     *
     * @param signPhone 营销活动服务明细-报名人手机
     */
    public void setSignPhone(String signPhone) {
        this.signPhone = signPhone == null ? null : signPhone.trim();
    }

    /**
     * 获取：营销活动服务明细-预约门店ID
     *
     * @return 预约门店ID
     */
    public Long getReservationStoreId() {
        return reservationStoreId;
    }

    /**
     * 设置：营销活动服务明细-预约门店ID
     *
     * @param reservationStoreId 营销活动服务明细-预约门店ID
     */
    public void setReservationStoreId(Long reservationStoreId) {
        this.reservationStoreId = reservationStoreId;
    }

    /**
     * 获取：营销活动服务明细-是否新用户
     *
     * @return 是否新用户
     */
    public String getIsNew() {
        return isNew;
    }

    /**
     * 设置：营销活动服务明细-是否新用户
     *
     * @param isNew 营销活动服务明细-是否新用户
     */
    public void setIsNew(String isNew) {
        this.isNew = isNew == null ? null : isNew.trim();
    }

    /**
     * 获取：营销活动服务明细-审核状态 0. 审核通过 1. 审核拒绝  2.取消预约
     *
     * @return 审核状态 0. 审核通过 1. 审核拒绝  2.取消预约
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * 设置：营销活动服务明细-审核状态 0. 审核通过 1. 审核拒绝  2.取消预约
     *
     * @param auditStatus 营销活动服务明细-审核状态 0. 审核通过 1. 审核拒绝  2.取消预约
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * 获取：营销活动服务明细-是否已经签到
     *
     * @return 是否已经签到
     */
    public String getIsSignIn() {
        return isSignIn;
    }

    /**
     * 设置：营销活动服务明细-是否已经签到
     *
     * @param isSignIn 营销活动服务明细-是否已经签到
     */
    public void setIsSignIn(String isSignIn) {
        this.isSignIn = isSignIn == null ? null : isSignIn.trim();
    }

    /**
     * 获取：营销活动服务明细-签到码
     *
     * @return 签到码
     */
    public String getSignInCode() {
        return signInCode;
    }

    /**
     * 设置：营销活动服务明细-签到码
     *
     * @param signInCode 营销活动服务明细-签到码
     */
    public void setSignInCode(String signInCode) {
        this.signInCode = signInCode == null ? null : signInCode.trim();
    }

    /**
     * 获取：营销活动服务明细-签到时间
     *
     * @return 签到时间
     */
    public String getSignInTime() {
        return signInTime;
    }

    /**
     * 设置：营销活动服务明细-签到时间
     *
     * @param signInTime 营销活动服务明细-签到时间
     */
    public void setSignInTime(String signInTime) {
        this.signInTime = signInTime == null ? null : signInTime.trim();
    }

    /**
     * 获取：营销活动服务明细-报名时间
     *
     * @return 报名时间
     */
    public String getSignTime() {
        return signTime;
    }

    /**
     * 设置：营销活动服务明细-报名时间
     *
     * @param signTime 营销活动服务明细-报名时间
     */
    public void setSignTime(String signTime) {
        this.signTime = signTime == null ? null : signTime.trim();
    }

    /**
     * 获取：营销活动服务明细-注册时间
     *
     * @return 注册时间
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * 设置：营销活动服务明细-注册时间
     *
     * @param registerTime 营销活动服务明细-注册时间
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * 获取：营销活动服务明细-奖励发放
     *
     * @return 奖励发放
     */
    public String getIsReward() {
        return isReward;
    }

    /**
     * 设置：营销活动服务明细-奖励发放
     *
     * @param isReward 营销活动服务明细-奖励发放
     */
    public void setIsReward(String isReward) {
        this.isReward = isReward == null ? null : isReward.trim();
    }

    /**
     * 获取：营销活动服务明细-预约时间段id
     *
     * @return 预约时间段id
     */
    public Long getReserveTimeId() {
        return reserveTimeId;
    }

    /**
     * 设置：营销活动服务明细-预约时间段id
     *
     * @param reserveTimeId 营销活动服务明细-预约时间段id
     */
    public void setReserveTimeId(Long reserveTimeId) {
        this.reserveTimeId = reserveTimeId;
    }

    /**
     * 获取：营销活动服务明细-活动ID
     *
     * @return 活动ID
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * 设置：营销活动服务明细-活动ID
     *
     * @param campaignId 营销活动服务明细-活动ID
     */
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * 获取：营销活动服务明细-签到用户姓名
     *
     * @return 签到用户姓名
     */
    public String getSignName() {
        return signName;
    }

    /**
     * 设置：营销活动服务明细-签到用户姓名
     *
     * @param signName 营销活动服务明细-签到用户姓名
     */
    public void setSignName(String signName) {
        this.signName = signName == null ? null : signName.trim();
    }
}