package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 活动反馈
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class CampaignFeedbackDO extends BaseModel implements Serializable {
    /**
     * 活动反馈-反馈类型：1-点击、2-报名、3-签到、4-分享、5-停留时长、6-邀请入会
     */
    private String feedbackType;

    /**
     * 活动反馈-开始时间
     */
    private Date startTime;

    /**
     * 活动反馈-结束时间
     */
    private Date endTime;

    /**
     * 活动反馈-客户移动设备（提交表单的用户收集此信息）
     */
    private String device;

    /**
     * 活动反馈-地理位置（提交表单的用户收集此信息）
     */
    private String location;

    /**
     * 活动反馈-渠道ID
     */
    private Long channelId;

    /**
     * 活动反馈-分享活动的会员ID
     */
    private Long shareMemberId;

    /**
     * 活动反馈-推荐人ID
     */
    private Long inviterContactId;

    /**
     * 活动反馈-导购员ID
     */
    private Long guideId;

    /**
     * 活动反馈-微信openId
     */
    private String wxOpenId;

    /**
     * 活动反馈-活动ID
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：活动反馈-反馈类型：1-点击、2-报名、3-签到、4-分享、5-停留时长、6-邀请入会
     *
     * @return 反馈类型：1-点击、2-报名、3-签到、4-分享、5-停留时长、6-邀请入会
     */
    public String getFeedbackType() {
        return feedbackType;
    }

    /**
     * 设置：活动反馈-反馈类型：1-点击、2-报名、3-签到、4-分享、5-停留时长、6-邀请入会
     *
     * @param feedbackType 活动反馈-反馈类型：1-点击、2-报名、3-签到、4-分享、5-停留时长、6-邀请入会
     */
    public void setFeedbackType(String feedbackType) {
        this.feedbackType = feedbackType == null ? null : feedbackType.trim();
    }

    /**
     * 获取：活动反馈-开始时间
     *
     * @return 开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * 设置：活动反馈-开始时间
     *
     * @param startTime 活动反馈-开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取：活动反馈-结束时间
     *
     * @return 结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置：活动反馈-结束时间
     *
     * @param endTime 活动反馈-结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取：活动反馈-客户移动设备（提交表单的用户收集此信息）
     *
     * @return 客户移动设备（提交表单的用户收集此信息）
     */
    public String getDevice() {
        return device;
    }

    /**
     * 设置：活动反馈-客户移动设备（提交表单的用户收集此信息）
     *
     * @param device 活动反馈-客户移动设备（提交表单的用户收集此信息）
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * 获取：活动反馈-地理位置（提交表单的用户收集此信息）
     *
     * @return 地理位置（提交表单的用户收集此信息）
     */
    public String getLocation() {
        return location;
    }

    /**
     * 设置：活动反馈-地理位置（提交表单的用户收集此信息）
     *
     * @param location 活动反馈-地理位置（提交表单的用户收集此信息）
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * 获取：活动反馈-渠道ID
     *
     * @return 渠道ID
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * 设置：活动反馈-渠道ID
     *
     * @param channelId 活动反馈-渠道ID
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * 获取：活动反馈-分享活动的会员ID
     *
     * @return 分享活动的会员ID
     */
    public Long getShareMemberId() {
        return shareMemberId;
    }

    /**
     * 设置：活动反馈-分享活动的会员ID
     *
     * @param shareMemberId 活动反馈-分享活动的会员ID
     */
    public void setShareMemberId(Long shareMemberId) {
        this.shareMemberId = shareMemberId;
    }

    /**
     * 获取：活动反馈-推荐人ID
     *
     * @return 推荐人ID
     */
    public Long getInviterContactId() {
        return inviterContactId;
    }

    /**
     * 设置：活动反馈-推荐人ID
     *
     * @param inviterContactId 活动反馈-推荐人ID
     */
    public void setInviterContactId(Long inviterContactId) {
        this.inviterContactId = inviterContactId;
    }

    /**
     * 获取：活动反馈-导购员ID
     *
     * @return 导购员ID
     */
    public Long getGuideId() {
        return guideId;
    }

    /**
     * 设置：活动反馈-导购员ID
     *
     * @param guideId 活动反馈-导购员ID
     */
    public void setGuideId(Long guideId) {
        this.guideId = guideId;
    }

    /**
     * 获取：活动反馈-微信openId
     *
     * @return 微信openId
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * 设置：活动反馈-微信openId
     *
     * @param wxOpenId 活动反馈-微信openId
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * 获取：活动反馈-活动ID
     *
     * @return 活动ID
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * 设置：活动反馈-活动ID
     *
     * @param campaignId 活动反馈-活动ID
     */
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }
}