package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 活动可预约时间段
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class CampaignReserveTimeDO extends BaseModel implements Serializable {
    /**
     * 活动可预约时间段-可预约开始时间
     */
    private Date reserveStartTime;

    /**
     * 活动可预约时间段-可预约结束时间
     */
    private Date reserveEndTime;

    /**
     * 活动可预约时间段-活动ID
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：活动可预约时间段-可预约开始时间
     *
     * @return 可预约开始时间
     */
    public Date getReserveStartTime() {
        return reserveStartTime;
    }

    /**
     * 设置：活动可预约时间段-可预约开始时间
     *
     * @param reserveStartTime 活动可预约时间段-可预约开始时间
     */
    public void setReserveStartTime(Date reserveStartTime) {
        this.reserveStartTime = reserveStartTime;
    }

    /**
     * 获取：活动可预约时间段-可预约结束时间
     *
     * @return 可预约结束时间
     */
    public Date getReserveEndTime() {
        return reserveEndTime;
    }

    /**
     * 设置：活动可预约时间段-可预约结束时间
     *
     * @param reserveEndTime 活动可预约时间段-可预约结束时间
     */
    public void setReserveEndTime(Date reserveEndTime) {
        this.reserveEndTime = reserveEndTime;
    }

    /**
     * 获取：活动可预约时间段-活动ID
     *
     * @return 活动ID
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * 设置：活动可预约时间段-活动ID
     *
     * @param campaignId 活动可预约时间段-活动ID
     */
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }
}