package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.alibaba.fastjson.JSONArray;
import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * CampaignDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-22
 */
public class CampaignDO extends BaseModel implements Serializable {
    /**
     * CampaignDO-活动名称
     */
    private String name;

    /**
     * CampaignDO-活动类型
     */
    private String campaignType;

    /**
     * CampaignDO-报名开始时间
     */
    private Date signStartTime;

    /**
     * CampaignDO-报名结束时间
     */
    private Date signEndTime;

    /**
     * CampaignDO-背景图片
     */
    private String backImg;

    /**
     * CampaignDO-活动报名按钮颜色
     */
    private String buttonColor;

    /**
     * CampaignDO-活动报名按钮文案
     */
    private String buttonText;

    /**
     * CampaignDO-联系人手机号
     */
    private String contactPhone;

    /**
     * CampaignDO-活动开始时间
     */
    private Date startTime;

    /**
     * CampaignDO-活动结束时间
     */
    private Date endTime;

    /**
     * CampaignDO-活动报名活动地点
     */
    private String location;

    /**
     * CampaignDO-活动链接地址
     */
    private String linkAddress;

    /**
     * CampaignDO-活动报名首图
     */
    private String richPic;

    /**
     * CampaignDO-报名必填信息
     */
    private String necessoryInfo;

    /**
     * CampaignDO-活动摘要
     */
    private String richDigest;

    /**
     * CampaignDO-活动详情
     */
    private String richDetail;

    /**
     * CampaignDO-H5访问地址
     */
    private String viewAddress;

    /**
     * CampaignDO-微信转发描述
     */
    private String wxDescription;

    /**
     * CampaignDO-微信转发图
     */
    private String wxPic;

    /**
     * CampaignDO-微信转发标题
     */
    private String wxTitle;

    /**
     * CampaignDO-活动人数
     */
    private Integer attendNumControl;

    /**
     * CampaignDO-是否审核
     */
    private String isAuditOpen;

    /**
     * CampaignDO-提交成功页面提示标题
     */
    private String submitTitle;

    /**
     * CampaignDO-提交成功页面提示描述
     */
    private String submitDescription;

    /**
     * CampaignDO-是否开启签到码
     */
    private String isSignInOpen;

    /**
     * CampaignDO-活动状态:[0]设计中,[1]审核中,[2]审核不通过,[3]未开始,[4]进行中,[5]暂停中,[6]已结束
     */
    private String campaignState;

    /**
     * CampaignDO-淘宝h5地址
     */
    private String tbUrl;

    /**
     * CampaignDO-微信h5地址
     */
    private String wxUrl;

    /**
     * CampaignDO-是否长期活动
     */
    private String isLongTermActivity;

    /**
     * CampaignDO-是否长期可预约
     */
    private String isLongTermReservation;

    /**
     * CampaignDO-可预约星期日
     */
    private String reservationSelectableWeekdays;

    /**
     * CampaignDO-可预约门店
     */
    private JSONArray reservationSelectableStores;

    /**
     * CampaignDO-可提前多少天进行预约
     */
    private Integer daysAheadReservation;

    /**
     * CampaignDO-公众号授权appId
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：CampaignDO-活动名称
     *
     * @return 活动名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置：CampaignDO-活动名称
     *
     * @param name CampaignDO-活动名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取：CampaignDO-活动类型
     *
     * @return 活动类型
     */
    public String getCampaignType() {
        return campaignType;
    }

    /**
     * 设置：CampaignDO-活动类型
     *
     * @param campaignType CampaignDO-活动类型
     */
    public void setCampaignType(String campaignType) {
        this.campaignType = campaignType == null ? null : campaignType.trim();
    }

    /**
     * 获取：CampaignDO-报名开始时间
     *
     * @return 报名开始时间
     */
    public Date getSignStartTime() {
        return signStartTime;
    }

    /**
     * 设置：CampaignDO-报名开始时间
     *
     * @param signStartTime CampaignDO-报名开始时间
     */
    public void setSignStartTime(Date signStartTime) {
        this.signStartTime = signStartTime;
    }

    /**
     * 获取：CampaignDO-报名结束时间
     *
     * @return 报名结束时间
     */
    public Date getSignEndTime() {
        return signEndTime;
    }

    /**
     * 设置：CampaignDO-报名结束时间
     *
     * @param signEndTime CampaignDO-报名结束时间
     */
    public void setSignEndTime(Date signEndTime) {
        this.signEndTime = signEndTime;
    }

    /**
     * 获取：CampaignDO-背景图片
     *
     * @return 背景图片
     */
    public String getBackImg() {
        return backImg;
    }

    /**
     * 设置：CampaignDO-背景图片
     *
     * @param backImg CampaignDO-背景图片
     */
    public void setBackImg(String backImg) {
        this.backImg = backImg == null ? null : backImg.trim();
    }

    /**
     * 获取：CampaignDO-活动报名按钮颜色
     *
     * @return 活动报名按钮颜色
     */
    public String getButtonColor() {
        return buttonColor;
    }

    /**
     * 设置：CampaignDO-活动报名按钮颜色
     *
     * @param buttonColor CampaignDO-活动报名按钮颜色
     */
    public void setButtonColor(String buttonColor) {
        this.buttonColor = buttonColor == null ? null : buttonColor.trim();
    }

    /**
     * 获取：CampaignDO-活动报名按钮文案
     *
     * @return 活动报名按钮文案
     */
    public String getButtonText() {
        return buttonText;
    }

    /**
     * 设置：CampaignDO-活动报名按钮文案
     *
     * @param buttonText CampaignDO-活动报名按钮文案
     */
    public void setButtonText(String buttonText) {
        this.buttonText = buttonText == null ? null : buttonText.trim();
    }

    /**
     * 获取：CampaignDO-联系人手机号
     *
     * @return 联系人手机号
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * 设置：CampaignDO-联系人手机号
     *
     * @param contactPhone CampaignDO-联系人手机号
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * 获取：CampaignDO-活动开始时间
     *
     * @return 活动开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * 设置：CampaignDO-活动开始时间
     *
     * @param startTime CampaignDO-活动开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取：CampaignDO-活动结束时间
     *
     * @return 活动结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置：CampaignDO-活动结束时间
     *
     * @param endTime CampaignDO-活动结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取：CampaignDO-活动报名活动地点
     *
     * @return 活动报名活动地点
     */
    public String getLocation() {
        return location;
    }

    /**
     * 设置：CampaignDO-活动报名活动地点
     *
     * @param location CampaignDO-活动报名活动地点
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * 获取：CampaignDO-活动链接地址
     *
     * @return 活动链接地址
     */
    public String getLinkAddress() {
        return linkAddress;
    }

    /**
     * 设置：CampaignDO-活动链接地址
     *
     * @param linkAddress CampaignDO-活动链接地址
     */
    public void setLinkAddress(String linkAddress) {
        this.linkAddress = linkAddress == null ? null : linkAddress.trim();
    }

    /**
     * 获取：CampaignDO-活动报名首图
     *
     * @return 活动报名首图
     */
    public String getRichPic() {
        return richPic;
    }

    /**
     * 设置：CampaignDO-活动报名首图
     *
     * @param richPic CampaignDO-活动报名首图
     */
    public void setRichPic(String richPic) {
        this.richPic = richPic == null ? null : richPic.trim();
    }

    /**
     * 获取：CampaignDO-报名必填信息
     *
     * @return 报名必填信息
     */
    public String getNecessoryInfo() {
        return necessoryInfo;
    }

    /**
     * 设置：CampaignDO-报名必填信息
     *
     * @param necessoryInfo CampaignDO-报名必填信息
     */
    public void setNecessoryInfo(String necessoryInfo) {
        this.necessoryInfo = necessoryInfo == null ? null : necessoryInfo.trim();
    }

    /**
     * 获取：CampaignDO-活动摘要
     *
     * @return 活动摘要
     */
    public String getRichDigest() {
        return richDigest;
    }

    /**
     * 设置：CampaignDO-活动摘要
     *
     * @param richDigest CampaignDO-活动摘要
     */
    public void setRichDigest(String richDigest) {
        this.richDigest = richDigest == null ? null : richDigest.trim();
    }

    /**
     * 获取：CampaignDO-活动详情
     *
     * @return 活动详情
     */
    public String getRichDetail() {
        return richDetail;
    }

    /**
     * 设置：CampaignDO-活动详情
     *
     * @param richDetail CampaignDO-活动详情
     */
    public void setRichDetail(String richDetail) {
        this.richDetail = richDetail == null ? null : richDetail.trim();
    }

    /**
     * 获取：CampaignDO-H5访问地址
     *
     * @return H5访问地址
     */
    public String getViewAddress() {
        return viewAddress;
    }

    /**
     * 设置：CampaignDO-H5访问地址
     *
     * @param viewAddress CampaignDO-H5访问地址
     */
    public void setViewAddress(String viewAddress) {
        this.viewAddress = viewAddress == null ? null : viewAddress.trim();
    }

    /**
     * 获取：CampaignDO-微信转发描述
     *
     * @return 微信转发描述
     */
    public String getWxDescription() {
        return wxDescription;
    }

    /**
     * 设置：CampaignDO-微信转发描述
     *
     * @param wxDescription CampaignDO-微信转发描述
     */
    public void setWxDescription(String wxDescription) {
        this.wxDescription = wxDescription == null ? null : wxDescription.trim();
    }

    /**
     * 获取：CampaignDO-微信转发图
     *
     * @return 微信转发图
     */
    public String getWxPic() {
        return wxPic;
    }

    /**
     * 设置：CampaignDO-微信转发图
     *
     * @param wxPic CampaignDO-微信转发图
     */
    public void setWxPic(String wxPic) {
        this.wxPic = wxPic == null ? null : wxPic.trim();
    }

    /**
     * 获取：CampaignDO-微信转发标题
     *
     * @return 微信转发标题
     */
    public String getWxTitle() {
        return wxTitle;
    }

    /**
     * 设置：CampaignDO-微信转发标题
     *
     * @param wxTitle CampaignDO-微信转发标题
     */
    public void setWxTitle(String wxTitle) {
        this.wxTitle = wxTitle == null ? null : wxTitle.trim();
    }

    /**
     * 获取：CampaignDO-活动人数
     *
     * @return 活动人数
     */
    public Integer getAttendNumControl() {
        return attendNumControl;
    }

    /**
     * 设置：CampaignDO-活动人数
     *
     * @param attendNumControl CampaignDO-活动人数
     */
    public void setAttendNumControl(Integer attendNumControl) {
        this.attendNumControl = attendNumControl;
    }

    /**
     * 获取：CampaignDO-是否审核
     *
     * @return 是否审核
     */
    public String getIsAuditOpen() {
        return isAuditOpen;
    }

    /**
     * 设置：CampaignDO-是否审核
     *
     * @param isAuditOpen CampaignDO-是否审核
     */
    public void setIsAuditOpen(String isAuditOpen) {
        this.isAuditOpen = isAuditOpen == null ? null : isAuditOpen.trim();
    }

    /**
     * 获取：CampaignDO-提交成功页面提示标题
     *
     * @return 提交成功页面提示标题
     */
    public String getSubmitTitle() {
        return submitTitle;
    }

    /**
     * 设置：CampaignDO-提交成功页面提示标题
     *
     * @param submitTitle CampaignDO-提交成功页面提示标题
     */
    public void setSubmitTitle(String submitTitle) {
        this.submitTitle = submitTitle == null ? null : submitTitle.trim();
    }

    /**
     * 获取：CampaignDO-提交成功页面提示描述
     *
     * @return 提交成功页面提示描述
     */
    public String getSubmitDescription() {
        return submitDescription;
    }

    /**
     * 设置：CampaignDO-提交成功页面提示描述
     *
     * @param submitDescription CampaignDO-提交成功页面提示描述
     */
    public void setSubmitDescription(String submitDescription) {
        this.submitDescription = submitDescription == null ? null : submitDescription.trim();
    }

    /**
     * 获取：CampaignDO-是否开启签到码
     *
     * @return 是否开启签到码
     */
    public String getIsSignInOpen() {
        return isSignInOpen;
    }

    /**
     * 设置：CampaignDO-是否开启签到码
     *
     * @param isSignInOpen CampaignDO-是否开启签到码
     */
    public void setIsSignInOpen(String isSignInOpen) {
        this.isSignInOpen = isSignInOpen == null ? null : isSignInOpen.trim();
    }

    /**
     * 获取：CampaignDO-活动状态:[0]设计中,[1]审核中,[2]审核不通过,[3]未开始,[4]进行中,[5]暂停中,[6]已结束
     *
     * @return 活动状态:[0]设计中,[1]审核中,[2]审核不通过,[3]未开始,[4]进行中,[5]暂停中,[6]已结束
     */
    public String getCampaignState() {
        return campaignState;
    }

    /**
     * 设置：CampaignDO-活动状态:[0]设计中,[1]审核中,[2]审核不通过,[3]未开始,[4]进行中,[5]暂停中,[6]已结束
     *
     * @param campaignState CampaignDO-活动状态:[0]设计中,[1]审核中,[2]审核不通过,[3]未开始,[4]进行中,[5]暂停中,[6]已结束
     */
    public void setCampaignState(String campaignState) {
        this.campaignState = campaignState == null ? null : campaignState.trim();
    }

    /**
     * 获取：CampaignDO-淘宝h5地址
     *
     * @return 淘宝h5地址
     */
    public String getTbUrl() {
        return tbUrl;
    }

    /**
     * 设置：CampaignDO-淘宝h5地址
     *
     * @param tbUrl CampaignDO-淘宝h5地址
     */
    public void setTbUrl(String tbUrl) {
        this.tbUrl = tbUrl == null ? null : tbUrl.trim();
    }

    /**
     * 获取：CampaignDO-微信h5地址
     *
     * @return 微信h5地址
     */
    public String getWxUrl() {
        return wxUrl;
    }

    /**
     * 设置：CampaignDO-微信h5地址
     *
     * @param wxUrl CampaignDO-微信h5地址
     */
    public void setWxUrl(String wxUrl) {
        this.wxUrl = wxUrl == null ? null : wxUrl.trim();
    }

    /**
     * 获取：CampaignDO-是否长期活动
     *
     * @return 是否长期活动
     */
    public String getIsLongTermActivity() {
        return isLongTermActivity;
    }

    /**
     * 设置：CampaignDO-是否长期活动
     *
     * @param isLongTermActivity CampaignDO-是否长期活动
     */
    public void setIsLongTermActivity(String isLongTermActivity) {
        this.isLongTermActivity = isLongTermActivity == null ? null : isLongTermActivity.trim();
    }

    /**
     * 获取：CampaignDO-是否长期可预约
     *
     * @return 是否长期可预约
     */
    public String getIsLongTermReservation() {
        return isLongTermReservation;
    }

    /**
     * 设置：CampaignDO-是否长期可预约
     *
     * @param isLongTermReservation CampaignDO-是否长期可预约
     */
    public void setIsLongTermReservation(String isLongTermReservation) {
        this.isLongTermReservation = isLongTermReservation == null ? null : isLongTermReservation.trim();
    }

    /**
     * 获取：CampaignDO-可预约星期日
     *
     * @return 可预约星期日
     */
    public String getReservationSelectableWeekdays() {
        return reservationSelectableWeekdays;
    }

    /**
     * 设置：CampaignDO-可预约星期日
     *
     * @param reservationSelectableWeekdays CampaignDO-可预约星期日
     */
    public void setReservationSelectableWeekdays(String reservationSelectableWeekdays) {
        this.reservationSelectableWeekdays = reservationSelectableWeekdays == null ? null : reservationSelectableWeekdays.trim();
    }

    /**
     * 获取：CampaignDO-可预约门店
     *
     * @return 可预约门店
     */
    public JSONArray getReservationSelectableStores() {
        return reservationSelectableStores;
    }

    /**
     * 设置：CampaignDO-可预约门店
     *
     * @param reservationSelectableStores CampaignDO-可预约门店
     */
    public void setReservationSelectableStores(JSONArray reservationSelectableStores) {
        this.reservationSelectableStores = reservationSelectableStores;
    }

    /**
     * 获取：CampaignDO-可提前多少天进行预约
     *
     * @return 可提前多少天进行预约
     */
    public Integer getDaysAheadReservation() {
        return daysAheadReservation;
    }

    /**
     * 设置：CampaignDO-可提前多少天进行预约
     *
     * @param daysAheadReservation CampaignDO-可提前多少天进行预约
     */
    public void setDaysAheadReservation(Integer daysAheadReservation) {
        this.daysAheadReservation = daysAheadReservation;
    }

    /**
     * 获取：CampaignDO-公众号授权appId
     *
     * @return 公众号授权appId
     */
    public String getAppid() {
        return appid;
    }

    /**
     * 设置：CampaignDO-公众号授权appId
     *
     * @param appid CampaignDO-公众号授权appId
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }
}