package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * EventTriggerHistoryDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-20
 */
public class EventTriggerHistoryDO extends BaseModel implements Serializable {
    /**
     * EventTriggerHistoryDO-事件编码
     */
    private String eventCode;

    /**
     * EventTriggerHistoryDO-触发会员ID
     */
    private Long memberId;

    /**
     * EventTriggerHistoryDO-会员名称
     */
    private String memberName;

    /**
     * EventTriggerHistoryDO-手机号
     */
    private String memberPhone;

    /**
     * EventTriggerHistoryDO-微信昵称
     */
    private String wxNickname;

    /**
     * EventTriggerHistoryDO-流程执行是否完成
     */
    private String isProcessFinished;

    /**
     * EventTriggerHistoryDO-营销流程定义ID
     */
    private Long marketingId;

    /**
     * EventTriggerHistoryDO-触发识别ID
     */
    private Long identifyId;

    /**
     * EventTriggerHistoryDO-触发识别编码
     */
    private String identifyCode;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：EventTriggerHistoryDO-事件编码
     *
     * @return 事件编码
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * 设置：EventTriggerHistoryDO-事件编码
     *
     * @param eventCode EventTriggerHistoryDO-事件编码
     */
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode == null ? null : eventCode.trim();
    }

    /**
     * 获取：EventTriggerHistoryDO-触发会员ID
     *
     * @return 触发会员ID
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * 设置：EventTriggerHistoryDO-触发会员ID
     *
     * @param memberId EventTriggerHistoryDO-触发会员ID
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * 获取：EventTriggerHistoryDO-会员名称
     *
     * @return 会员名称
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * 设置：EventTriggerHistoryDO-会员名称
     *
     * @param memberName EventTriggerHistoryDO-会员名称
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * 获取：EventTriggerHistoryDO-手机号
     *
     * @return 手机号
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * 设置：EventTriggerHistoryDO-手机号
     *
     * @param memberPhone EventTriggerHistoryDO-手机号
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * 获取：EventTriggerHistoryDO-微信昵称
     *
     * @return 微信昵称
     */
    public String getWxNickname() {
        return wxNickname;
    }

    /**
     * 设置：EventTriggerHistoryDO-微信昵称
     *
     * @param wxNickname EventTriggerHistoryDO-微信昵称
     */
    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname == null ? null : wxNickname.trim();
    }

    /**
     * 获取：EventTriggerHistoryDO-流程执行是否完成
     *
     * @return 流程执行是否完成
     */
    public String getIsProcessFinished() {
        return isProcessFinished;
    }

    /**
     * 设置：EventTriggerHistoryDO-流程执行是否完成
     *
     * @param isProcessFinished EventTriggerHistoryDO-流程执行是否完成
     */
    public void setIsProcessFinished(String isProcessFinished) {
        this.isProcessFinished = isProcessFinished == null ? null : isProcessFinished.trim();
    }

    /**
     * 获取：EventTriggerHistoryDO-营销流程定义ID
     *
     * @return 营销流程定义ID
     */
    public Long getMarketingId() {
        return marketingId;
    }

    /**
     * 设置：EventTriggerHistoryDO-营销流程定义ID
     *
     * @param marketingId EventTriggerHistoryDO-营销流程定义ID
     */
    public void setMarketingId(Long marketingId) {
        this.marketingId = marketingId;
    }

    /**
     * 获取：EventTriggerHistoryDO-触发识别ID
     *
     * @return 触发识别ID
     */
    public Long getIdentifyId() {
        return identifyId;
    }

    /**
     * 设置：EventTriggerHistoryDO-触发识别ID
     *
     * @param identifyId EventTriggerHistoryDO-触发识别ID
     */
    public void setIdentifyId(Long identifyId) {
        this.identifyId = identifyId;
    }

    /**
     * 获取：EventTriggerHistoryDO-触发识别编码
     *
     * @return 触发识别编码
     */
    public String getIdentifyCode() {
        return identifyCode;
    }

    /**
     * 设置：EventTriggerHistoryDO-触发识别编码
     *
     * @param identifyCode EventTriggerHistoryDO-触发识别编码
     */
    public void setIdentifyCode(String identifyCode) {
        this.identifyCode = identifyCode == null ? null : identifyCode.trim();
    }
}