package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 事件轨迹表
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class EventTraceDO extends BaseModel implements Serializable {
    /**
     * 事件轨迹表-事件ID
     */
    private Long eventId;

    /**
     * 事件轨迹表-会员ID
     */
    private Long memberId;

    /**
     * 事件轨迹表-语言: zh 中文，en 英文
     */
    private String lang;

    /**
     * 事件轨迹表-内容
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：事件轨迹表-事件ID
     *
     * @return 事件ID
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * 设置：事件轨迹表-事件ID
     *
     * @param eventId 事件轨迹表-事件ID
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * 获取：事件轨迹表-会员ID
     *
     * @return 会员ID
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * 设置：事件轨迹表-会员ID
     *
     * @param memberId 事件轨迹表-会员ID
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * 获取：事件轨迹表-语言: zh 中文，en 英文
     *
     * @return 语言: zh 中文，en 英文
     */
    public String getLang() {
        return lang;
    }

    /**
     * 设置：事件轨迹表-语言: zh 中文，en 英文
     *
     * @param lang 事件轨迹表-语言: zh 中文，en 英文
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * 获取：事件轨迹表-内容
     *
     * @return 内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置：事件轨迹表-内容
     *
     * @param content 事件轨迹表-内容
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}