package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 营销流程动作预制
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingActionPresetDO extends BaseModel implements Serializable {
    /**
     * 营销流程动作预制-动作名称
     */
    private String actionName;

    /**
     * 营销流程动作预制-动作类型:[0]发短信,[3]赠送积分,[4]添加优惠券,[6]打标签
     */
    private String actionType;

    /**
     * 营销流程动作预制-动作执行的java类(含包名)
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：营销流程动作预制-动作名称
     *
     * @return 动作名称
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * 设置：营销流程动作预制-动作名称
     *
     * @param actionName 营销流程动作预制-动作名称
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * 获取：营销流程动作预制-动作类型:[0]发短信,[3]赠送积分,[4]添加优惠券,[6]打标签
     *
     * @return 动作类型:[0]发短信,[3]赠送积分,[4]添加优惠券,[6]打标签
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * 设置：营销流程动作预制-动作类型:[0]发短信,[3]赠送积分,[4]添加优惠券,[6]打标签
     *
     * @param actionType 营销流程动作预制-动作类型:[0]发短信,[3]赠送积分,[4]添加优惠券,[6]打标签
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * 获取：营销流程动作预制-动作执行的java类(含包名)
     *
     * @return 动作执行的java类(含包名)
     */
    public String getClassName() {
        return className;
    }

    /**
     * 设置：营销流程动作预制-动作执行的java类(含包名)
     *
     * @param className 营销流程动作预制-动作执行的java类(含包名)
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}