package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 营销流程定义
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingDefineDO extends BaseModel implements Serializable {
    /**
     * 营销流程定义-模板ID
     */
    private Long templateId;

    /**
     * 营销流程定义-营销流程名称
     */
    private String marketingName;

    /**
     * 营销流程定义-营销流程备注
     */
    private String marketingRemark;

    /**
     * 营销流程定义-订单分析起始
     */
    private Date analysisStart;

    /**
     * 营销流程定义-订单分析结束
     */
    private Date analysisEnd;

    /**
     * 营销流程定义-是否相对日期:[0]否,[1]是
     */
    private String isRelative;

    /**
     * 营销流程定义-向前推移天数
     */
    private Integer beforeCount;

    /**
     * 营销流程定义-向后推移天数
     */
    private Integer afterCount;

    /**
     * 营销流程定义-营销类型:[1]主动营销,[2]事件营销
     */
    private String marketingType;

    /**
     * 营销流程定义-营销配置json信息
     */
    private String marketingConfigJson;

    /**
     * 营销流程定义-流程执行配置json信息
     */
    private String excuteConfigJson;

    /**
     * 营销流程定义-是否永久有效:[0]否,[1]是
     */
    private String isAlwaysValid;

    /**
     * 营销流程定义-开始时间
     */
    private Date starttime;

    /**
     * 营销流程定义-结束时间
     */
    private Date finishtime;

    /**
     * 营销流程定义-触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     */
    private String frequenceType;

    /**
     * 营销流程定义-频次数量
     */
    private Integer frequenceCount;

    /**
     * 营销流程定义-频次单位:[0]天,[1]周,[2]月
     */
    private String frequenceUnit;

    /**
     * 营销流程定义-营销流程状态:[0]设计中,[1]生效,[2]失效
     */
    private String marketingStatus;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：营销流程定义-模板ID
     *
     * @return 模板ID
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * 设置：营销流程定义-模板ID
     *
     * @param templateId 营销流程定义-模板ID
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * 获取：营销流程定义-营销流程名称
     *
     * @return 营销流程名称
     */
    public String getMarketingName() {
        return marketingName;
    }

    /**
     * 设置：营销流程定义-营销流程名称
     *
     * @param marketingName 营销流程定义-营销流程名称
     */
    public void setMarketingName(String marketingName) {
        this.marketingName = marketingName == null ? null : marketingName.trim();
    }

    /**
     * 获取：营销流程定义-营销流程备注
     *
     * @return 营销流程备注
     */
    public String getMarketingRemark() {
        return marketingRemark;
    }

    /**
     * 设置：营销流程定义-营销流程备注
     *
     * @param marketingRemark 营销流程定义-营销流程备注
     */
    public void setMarketingRemark(String marketingRemark) {
        this.marketingRemark = marketingRemark == null ? null : marketingRemark.trim();
    }

    /**
     * 获取：营销流程定义-订单分析起始
     *
     * @return 订单分析起始
     */
    public Date getAnalysisStart() {
        return analysisStart;
    }

    /**
     * 设置：营销流程定义-订单分析起始
     *
     * @param analysisStart 营销流程定义-订单分析起始
     */
    public void setAnalysisStart(Date analysisStart) {
        this.analysisStart = analysisStart;
    }

    /**
     * 获取：营销流程定义-订单分析结束
     *
     * @return 订单分析结束
     */
    public Date getAnalysisEnd() {
        return analysisEnd;
    }

    /**
     * 设置：营销流程定义-订单分析结束
     *
     * @param analysisEnd 营销流程定义-订单分析结束
     */
    public void setAnalysisEnd(Date analysisEnd) {
        this.analysisEnd = analysisEnd;
    }

    /**
     * 获取：营销流程定义-是否相对日期:[0]否,[1]是
     *
     * @return 是否相对日期:[0]否,[1]是
     */
    public String getIsRelative() {
        return isRelative;
    }

    /**
     * 设置：营销流程定义-是否相对日期:[0]否,[1]是
     *
     * @param isRelative 营销流程定义-是否相对日期:[0]否,[1]是
     */
    public void setIsRelative(String isRelative) {
        this.isRelative = isRelative == null ? null : isRelative.trim();
    }

    /**
     * 获取：营销流程定义-向前推移天数
     *
     * @return 向前推移天数
     */
    public Integer getBeforeCount() {
        return beforeCount;
    }

    /**
     * 设置：营销流程定义-向前推移天数
     *
     * @param beforeCount 营销流程定义-向前推移天数
     */
    public void setBeforeCount(Integer beforeCount) {
        this.beforeCount = beforeCount;
    }

    /**
     * 获取：营销流程定义-向后推移天数
     *
     * @return 向后推移天数
     */
    public Integer getAfterCount() {
        return afterCount;
    }

    /**
     * 设置：营销流程定义-向后推移天数
     *
     * @param afterCount 营销流程定义-向后推移天数
     */
    public void setAfterCount(Integer afterCount) {
        this.afterCount = afterCount;
    }

    /**
     * 获取：营销流程定义-营销类型:[1]主动营销,[2]事件营销
     *
     * @return 营销类型:[1]主动营销,[2]事件营销
     */
    public String getMarketingType() {
        return marketingType;
    }

    /**
     * 设置：营销流程定义-营销类型:[1]主动营销,[2]事件营销
     *
     * @param marketingType 营销流程定义-营销类型:[1]主动营销,[2]事件营销
     */
    public void setMarketingType(String marketingType) {
        this.marketingType = marketingType == null ? null : marketingType.trim();
    }

    /**
     * 获取：营销流程定义-营销配置json信息
     *
     * @return 营销配置json信息
     */
    public String getMarketingConfigJson() {
        return marketingConfigJson;
    }

    /**
     * 设置：营销流程定义-营销配置json信息
     *
     * @param marketingConfigJson 营销流程定义-营销配置json信息
     */
    public void setMarketingConfigJson(String marketingConfigJson) {
        this.marketingConfigJson = marketingConfigJson == null ? null : marketingConfigJson.trim();
    }

    /**
     * 获取：营销流程定义-流程执行配置json信息
     *
     * @return 流程执行配置json信息
     */
    public String getExcuteConfigJson() {
        return excuteConfigJson;
    }

    /**
     * 设置：营销流程定义-流程执行配置json信息
     *
     * @param excuteConfigJson 营销流程定义-流程执行配置json信息
     */
    public void setExcuteConfigJson(String excuteConfigJson) {
        this.excuteConfigJson = excuteConfigJson == null ? null : excuteConfigJson.trim();
    }

    /**
     * 获取：营销流程定义-是否永久有效:[0]否,[1]是
     *
     * @return 是否永久有效:[0]否,[1]是
     */
    public String getIsAlwaysValid() {
        return isAlwaysValid;
    }

    /**
     * 设置：营销流程定义-是否永久有效:[0]否,[1]是
     *
     * @param isAlwaysValid 营销流程定义-是否永久有效:[0]否,[1]是
     */
    public void setIsAlwaysValid(String isAlwaysValid) {
        this.isAlwaysValid = isAlwaysValid == null ? null : isAlwaysValid.trim();
    }

    /**
     * 获取：营销流程定义-开始时间
     *
     * @return 开始时间
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * 设置：营销流程定义-开始时间
     *
     * @param starttime 营销流程定义-开始时间
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * 获取：营销流程定义-结束时间
     *
     * @return 结束时间
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * 设置：营销流程定义-结束时间
     *
     * @param finishtime 营销流程定义-结束时间
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * 获取：营销流程定义-触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     *
     * @return 触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     */
    public String getFrequenceType() {
        return frequenceType;
    }

    /**
     * 设置：营销流程定义-触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     *
     * @param frequenceType 营销流程定义-触发频次类型:[0]不限制,[1]每个客户仅能触发一次,[2]每个客户在一段时间内仅触发一次
     */
    public void setFrequenceType(String frequenceType) {
        this.frequenceType = frequenceType == null ? null : frequenceType.trim();
    }

    /**
     * 获取：营销流程定义-频次数量
     *
     * @return 频次数量
     */
    public Integer getFrequenceCount() {
        return frequenceCount;
    }

    /**
     * 设置：营销流程定义-频次数量
     *
     * @param frequenceCount 营销流程定义-频次数量
     */
    public void setFrequenceCount(Integer frequenceCount) {
        this.frequenceCount = frequenceCount;
    }

    /**
     * 获取：营销流程定义-频次单位:[0]天,[1]周,[2]月
     *
     * @return 频次单位:[0]天,[1]周,[2]月
     */
    public String getFrequenceUnit() {
        return frequenceUnit;
    }

    /**
     * 设置：营销流程定义-频次单位:[0]天,[1]周,[2]月
     *
     * @param frequenceUnit 营销流程定义-频次单位:[0]天,[1]周,[2]月
     */
    public void setFrequenceUnit(String frequenceUnit) {
        this.frequenceUnit = frequenceUnit == null ? null : frequenceUnit.trim();
    }

    /**
     * 获取：营销流程定义-营销流程状态:[0]设计中,[1]生效,[2]失效
     *
     * @return 营销流程状态:[0]设计中,[1]生效,[2]失效
     */
    public String getMarketingStatus() {
        return marketingStatus;
    }

    /**
     * 设置：营销流程定义-营销流程状态:[0]设计中,[1]生效,[2]失效
     *
     * @param marketingStatus 营销流程定义-营销流程状态:[0]设计中,[1]生效,[2]失效
     */
    public void setMarketingStatus(String marketingStatus) {
        this.marketingStatus = marketingStatus == null ? null : marketingStatus.trim();
    }
}