package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 营销流程模板
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingTemplateDO extends BaseModel implements Serializable {
    /**
     * 营销流程模板-template_name
     */
    private String templateName;

    /**
     * 营销流程模板-流程配置json信息
     */
    private String marketingConfigJson;

    /**
     * 营销流程模板-营销类型:[1]主动营销,[2]事件营销
     */
    private String marketingType;

    /**
     * 营销流程模板-template_picture
     */
    private String templatePicture;

    /**
     * 营销流程模板-template_description
     */
    private String templateDescription;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：营销流程模板-template_name
     *
     * @return template_name
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * 设置：营销流程模板-template_name
     *
     * @param templateName
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * 获取：营销流程模板-流程配置json信息
     *
     * @return 流程配置json信息
     */
    public String getMarketingConfigJson() {
        return marketingConfigJson;
    }

    /**
     * 设置：营销流程模板-流程配置json信息
     *
     * @param marketingConfigJson 营销流程模板-流程配置json信息
     */
    public void setMarketingConfigJson(String marketingConfigJson) {
        this.marketingConfigJson = marketingConfigJson == null ? null : marketingConfigJson.trim();
    }

    /**
     * 获取：营销流程模板-营销类型:[1]主动营销,[2]事件营销
     *
     * @return 营销类型:[1]主动营销,[2]事件营销
     */
    public String getMarketingType() {
        return marketingType;
    }

    /**
     * 设置：营销流程模板-营销类型:[1]主动营销,[2]事件营销
     *
     * @param marketingType 营销流程模板-营销类型:[1]主动营销,[2]事件营销
     */
    public void setMarketingType(String marketingType) {
        this.marketingType = marketingType == null ? null : marketingType.trim();
    }

    /**
     * 获取：营销流程模板-template_picture
     *
     * @return template_picture
     */
    public String getTemplatePicture() {
        return templatePicture;
    }

    /**
     * 设置：营销流程模板-template_picture
     *
     * @param templatePicture
     */
    public void setTemplatePicture(String templatePicture) {
        this.templatePicture = templatePicture == null ? null : templatePicture.trim();
    }

    /**
     * 获取：营销流程模板-template_description
     *
     * @return template_description
     */
    public String getTemplateDescription() {
        return templateDescription;
    }

    /**
     * 设置：营销流程模板-template_description
     *
     * @param templateDescription
     */
    public void setTemplateDescription(String templateDescription) {
        this.templateDescription = templateDescription == null ? null : templateDescription.trim();
    }
}