package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 渠道记录
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingChannelDO extends BaseModel implements Serializable {
    /**
     * 渠道记录-流程定义中的节点ID
     */
    private Integer nodeId;

    /**
     * 渠道记录-渠道类型
     */
    private String channelType;

    /**
     * 渠道记录-失败状态码
     */
    private String failCode;

    /**
     * 渠道记录-失败次数
     */
    private Integer failCounter;

    /**
     * 渠道记录-失败信息
     */
    private String failMsg;

    /**
     * 渠道记录-消息内容
     */
    private String msgContent;

    /**
     * 渠道记录-消息状态
     */
    private String msgStatus;

    /**
     * 渠道记录-发送时间
     */
    private Date releaseTime;

    /**
     * 渠道记录-立即发送
     */
    private String sendnow;

    /**
     * 渠道记录-发送次数
     */
    private Integer sentCounter;

    /**
     * 渠道记录-成功次数
     */
    private Integer successCounter;

    /**
     * 渠道记录-目标客户组
     */
    private Long targetGroup;

    /**
     * 渠道记录-目标手机
     */
    private String targetPhoneList;

    /**
     * 渠道记录-过滤条件
     */
    private String filterCondition;

    /**
     * 渠道记录-抄送手机列表
     */
    private String ccPhoneList;

    /**
     * 渠道记录-是否周期执行
     */
    private String isRepeat;

    /**
     * 渠道记录-周期类型
     */
    private String repeatType;

    /**
     * 渠道记录-微信群发ID
     */
    private String wxMsgId;

    /**
     * 渠道记录-过滤条件json串
     */
    private String filterConditionJson;

    /**
     * 渠道记录-机构名称
     */
    private String title;

    /**
     * 渠道记录-是否发送给全部微信粉丝
     */
    private String isAllWxfans;

    /**
     * 渠道记录-原始客户群
     */
    private Long originGroup;

    /**
     * 渠道记录-短信模板
     */
    private Long smsTemplateId;

    /**
     * 渠道记录-外呼业务类型
     */
    private Integer activeCallTypeId;

    /**
     * 渠道记录-到期时间
     */
    private Date dueDate;

    /**
     * 渠道记录-调查ID（survey_id）
     */
    private Long surveyId;

    /**
     * 渠道记录-描述
     */
    private String description;

    /**
     * 渠道记录-渠道H5地址
     */
    private String h5ChannelUrl;

    /**
     * 渠道记录-微信媒体ID
     */
    private String wxMediaId;

    /**
     * 渠道记录-优惠券编码
     */
    private String couponCode;

    /**
     * 渠道记录-活动H5 id
     */
    private Long campaignH5Id;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：渠道记录-流程定义中的节点ID
     *
     * @return 流程定义中的节点ID
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * 设置：渠道记录-流程定义中的节点ID
     *
     * @param nodeId 渠道记录-流程定义中的节点ID
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * 获取：渠道记录-渠道类型
     *
     * @return 渠道类型
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * 设置：渠道记录-渠道类型
     *
     * @param channelType 渠道记录-渠道类型
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * 获取：渠道记录-失败状态码
     *
     * @return 失败状态码
     */
    public String getFailCode() {
        return failCode;
    }

    /**
     * 设置：渠道记录-失败状态码
     *
     * @param failCode 渠道记录-失败状态码
     */
    public void setFailCode(String failCode) {
        this.failCode = failCode == null ? null : failCode.trim();
    }

    /**
     * 获取：渠道记录-失败次数
     *
     * @return 失败次数
     */
    public Integer getFailCounter() {
        return failCounter;
    }

    /**
     * 设置：渠道记录-失败次数
     *
     * @param failCounter 渠道记录-失败次数
     */
    public void setFailCounter(Integer failCounter) {
        this.failCounter = failCounter;
    }

    /**
     * 获取：渠道记录-失败信息
     *
     * @return 失败信息
     */
    public String getFailMsg() {
        return failMsg;
    }

    /**
     * 设置：渠道记录-失败信息
     *
     * @param failMsg 渠道记录-失败信息
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg == null ? null : failMsg.trim();
    }

    /**
     * 获取：渠道记录-消息内容
     *
     * @return 消息内容
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * 设置：渠道记录-消息内容
     *
     * @param msgContent 渠道记录-消息内容
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * 获取：渠道记录-消息状态
     *
     * @return 消息状态
     */
    public String getMsgStatus() {
        return msgStatus;
    }

    /**
     * 设置：渠道记录-消息状态
     *
     * @param msgStatus 渠道记录-消息状态
     */
    public void setMsgStatus(String msgStatus) {
        this.msgStatus = msgStatus == null ? null : msgStatus.trim();
    }

    /**
     * 获取：渠道记录-发送时间
     *
     * @return 发送时间
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * 设置：渠道记录-发送时间
     *
     * @param releaseTime 渠道记录-发送时间
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * 获取：渠道记录-立即发送
     *
     * @return 立即发送
     */
    public String getSendnow() {
        return sendnow;
    }

    /**
     * 设置：渠道记录-立即发送
     *
     * @param sendnow 渠道记录-立即发送
     */
    public void setSendnow(String sendnow) {
        this.sendnow = sendnow == null ? null : sendnow.trim();
    }

    /**
     * 获取：渠道记录-发送次数
     *
     * @return 发送次数
     */
    public Integer getSentCounter() {
        return sentCounter;
    }

    /**
     * 设置：渠道记录-发送次数
     *
     * @param sentCounter 渠道记录-发送次数
     */
    public void setSentCounter(Integer sentCounter) {
        this.sentCounter = sentCounter;
    }

    /**
     * 获取：渠道记录-成功次数
     *
     * @return 成功次数
     */
    public Integer getSuccessCounter() {
        return successCounter;
    }

    /**
     * 设置：渠道记录-成功次数
     *
     * @param successCounter 渠道记录-成功次数
     */
    public void setSuccessCounter(Integer successCounter) {
        this.successCounter = successCounter;
    }

    /**
     * 获取：渠道记录-目标客户组
     *
     * @return 目标客户组
     */
    public Long getTargetGroup() {
        return targetGroup;
    }

    /**
     * 设置：渠道记录-目标客户组
     *
     * @param targetGroup 渠道记录-目标客户组
     */
    public void setTargetGroup(Long targetGroup) {
        this.targetGroup = targetGroup;
    }

    /**
     * 获取：渠道记录-目标手机
     *
     * @return 目标手机
     */
    public String getTargetPhoneList() {
        return targetPhoneList;
    }

    /**
     * 设置：渠道记录-目标手机
     *
     * @param targetPhoneList 渠道记录-目标手机
     */
    public void setTargetPhoneList(String targetPhoneList) {
        this.targetPhoneList = targetPhoneList == null ? null : targetPhoneList.trim();
    }

    /**
     * 获取：渠道记录-过滤条件
     *
     * @return 过滤条件
     */
    public String getFilterCondition() {
        return filterCondition;
    }

    /**
     * 设置：渠道记录-过滤条件
     *
     * @param filterCondition 渠道记录-过滤条件
     */
    public void setFilterCondition(String filterCondition) {
        this.filterCondition = filterCondition == null ? null : filterCondition.trim();
    }

    /**
     * 获取：渠道记录-抄送手机列表
     *
     * @return 抄送手机列表
     */
    public String getCcPhoneList() {
        return ccPhoneList;
    }

    /**
     * 设置：渠道记录-抄送手机列表
     *
     * @param ccPhoneList 渠道记录-抄送手机列表
     */
    public void setCcPhoneList(String ccPhoneList) {
        this.ccPhoneList = ccPhoneList == null ? null : ccPhoneList.trim();
    }

    /**
     * 获取：渠道记录-是否周期执行
     *
     * @return 是否周期执行
     */
    public String getIsRepeat() {
        return isRepeat;
    }

    /**
     * 设置：渠道记录-是否周期执行
     *
     * @param isRepeat 渠道记录-是否周期执行
     */
    public void setIsRepeat(String isRepeat) {
        this.isRepeat = isRepeat == null ? null : isRepeat.trim();
    }

    /**
     * 获取：渠道记录-周期类型
     *
     * @return 周期类型
     */
    public String getRepeatType() {
        return repeatType;
    }

    /**
     * 设置：渠道记录-周期类型
     *
     * @param repeatType 渠道记录-周期类型
     */
    public void setRepeatType(String repeatType) {
        this.repeatType = repeatType == null ? null : repeatType.trim();
    }

    /**
     * 获取：渠道记录-微信群发ID
     *
     * @return 微信群发ID
     */
    public String getWxMsgId() {
        return wxMsgId;
    }

    /**
     * 设置：渠道记录-微信群发ID
     *
     * @param wxMsgId 渠道记录-微信群发ID
     */
    public void setWxMsgId(String wxMsgId) {
        this.wxMsgId = wxMsgId == null ? null : wxMsgId.trim();
    }

    /**
     * 获取：渠道记录-过滤条件json串
     *
     * @return 过滤条件json串
     */
    public String getFilterConditionJson() {
        return filterConditionJson;
    }

    /**
     * 设置：渠道记录-过滤条件json串
     *
     * @param filterConditionJson 渠道记录-过滤条件json串
     */
    public void setFilterConditionJson(String filterConditionJson) {
        this.filterConditionJson = filterConditionJson == null ? null : filterConditionJson.trim();
    }

    /**
     * 获取：渠道记录-机构名称
     *
     * @return 机构名称
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置：渠道记录-机构名称
     *
     * @param title 渠道记录-机构名称
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取：渠道记录-是否发送给全部微信粉丝
     *
     * @return 是否发送给全部微信粉丝
     */
    public String getIsAllWxfans() {
        return isAllWxfans;
    }

    /**
     * 设置：渠道记录-是否发送给全部微信粉丝
     *
     * @param isAllWxfans 渠道记录-是否发送给全部微信粉丝
     */
    public void setIsAllWxfans(String isAllWxfans) {
        this.isAllWxfans = isAllWxfans == null ? null : isAllWxfans.trim();
    }

    /**
     * 获取：渠道记录-原始客户群
     *
     * @return 原始客户群
     */
    public Long getOriginGroup() {
        return originGroup;
    }

    /**
     * 设置：渠道记录-原始客户群
     *
     * @param originGroup 渠道记录-原始客户群
     */
    public void setOriginGroup(Long originGroup) {
        this.originGroup = originGroup;
    }

    /**
     * 获取：渠道记录-短信模板
     *
     * @return 短信模板
     */
    public Long getSmsTemplateId() {
        return smsTemplateId;
    }

    /**
     * 设置：渠道记录-短信模板
     *
     * @param smsTemplateId 渠道记录-短信模板
     */
    public void setSmsTemplateId(Long smsTemplateId) {
        this.smsTemplateId = smsTemplateId;
    }

    /**
     * 获取：渠道记录-外呼业务类型
     *
     * @return 外呼业务类型
     */
    public Integer getActiveCallTypeId() {
        return activeCallTypeId;
    }

    /**
     * 设置：渠道记录-外呼业务类型
     *
     * @param activeCallTypeId 渠道记录-外呼业务类型
     */
    public void setActiveCallTypeId(Integer activeCallTypeId) {
        this.activeCallTypeId = activeCallTypeId;
    }

    /**
     * 获取：渠道记录-到期时间
     *
     * @return 到期时间
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * 设置：渠道记录-到期时间
     *
     * @param dueDate 渠道记录-到期时间
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * 获取：渠道记录-调查ID（survey_id）
     *
     * @return 调查ID（survey_id）
     */
    public Long getSurveyId() {
        return surveyId;
    }

    /**
     * 设置：渠道记录-调查ID（survey_id）
     *
     * @param surveyId 渠道记录-调查ID（survey_id）
     */
    public void setSurveyId(Long surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * 获取：渠道记录-描述
     *
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置：渠道记录-描述
     *
     * @param description 渠道记录-描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取：渠道记录-渠道H5地址
     *
     * @return 渠道H5地址
     */
    public String getH5ChannelUrl() {
        return h5ChannelUrl;
    }

    /**
     * 设置：渠道记录-渠道H5地址
     *
     * @param h5ChannelUrl 渠道记录-渠道H5地址
     */
    public void setH5ChannelUrl(String h5ChannelUrl) {
        this.h5ChannelUrl = h5ChannelUrl == null ? null : h5ChannelUrl.trim();
    }

    /**
     * 获取：渠道记录-微信媒体ID
     *
     * @return 微信媒体ID
     */
    public String getWxMediaId() {
        return wxMediaId;
    }

    /**
     * 设置：渠道记录-微信媒体ID
     *
     * @param wxMediaId 渠道记录-微信媒体ID
     */
    public void setWxMediaId(String wxMediaId) {
        this.wxMediaId = wxMediaId == null ? null : wxMediaId.trim();
    }

    /**
     * 获取：渠道记录-优惠券编码
     *
     * @return 优惠券编码
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * 设置：渠道记录-优惠券编码
     *
     * @param couponCode 渠道记录-优惠券编码
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode == null ? null : couponCode.trim();
    }

    /**
     * 获取：渠道记录-活动H5 id
     *
     * @return 活动H5 id
     */
    public Long getCampaignH5Id() {
        return campaignH5Id;
    }

    /**
     * 设置：渠道记录-活动H5 id
     *
     * @param campaignH5Id 渠道记录-活动H5 id
     */
    public void setCampaignH5Id(Long campaignH5Id) {
        this.campaignH5Id = campaignH5Id;
    }
}