package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 营销流程事件预制
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingEventPresetDO extends BaseModel implements Serializable {
    /**
     * 营销流程事件预制-事件名称
     */
    private String eventName;

    /**
     * 营销流程事件预制-条件组装关系
     */
    private String formular;

    /**
     * 营销流程事件预制-事件码,用于区分不同的事件
     */
    private String eventCode;

    /**
     * 营销流程事件预制-筛选条件
     */
    private String eventFilter;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：营销流程事件预制-事件名称
     *
     * @return 事件名称
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * 设置：营销流程事件预制-事件名称
     *
     * @param eventName 营销流程事件预制-事件名称
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * 获取：营销流程事件预制-条件组装关系
     *
     * @return 条件组装关系
     */
    public String getFormular() {
        return formular;
    }

    /**
     * 设置：营销流程事件预制-条件组装关系
     *
     * @param formular 营销流程事件预制-条件组装关系
     */
    public void setFormular(String formular) {
        this.formular = formular == null ? null : formular.trim();
    }

    /**
     * 获取：营销流程事件预制-事件码,用于区分不同的事件
     *
     * @return 事件码,用于区分不同的事件
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * 设置：营销流程事件预制-事件码,用于区分不同的事件
     *
     * @param eventCode 营销流程事件预制-事件码,用于区分不同的事件
     */
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode == null ? null : eventCode.trim();
    }

    /**
     * 获取：营销流程事件预制-筛选条件
     *
     * @return 筛选条件
     */
    public String getEventFilter() {
        return eventFilter;
    }

    /**
     * 设置：营销流程事件预制-筛选条件
     *
     * @param eventFilter 营销流程事件预制-筛选条件
     */
    public void setEventFilter(String eventFilter) {
        this.eventFilter = eventFilter == null ? null : eventFilter.trim();
    }
}