package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 * 活动流程执行实例历史
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class MarketingInstanceHistoryDO extends BaseModel implements Serializable {
    /**
     * 活动流程执行实例历史-当前执行步骤
     */
    private Integer step;

    /**
     * 活动流程执行实例历史-执行时间
     */
    private Date executeTime;

    /**
     * 活动流程执行实例历史-结果名称
     */
    private String result;

    /**
     * 活动流程执行实例历史-订单分析起始
     */
    private Date analysisStart;

    /**
     * 活动流程执行实例历史-订单分析结束
     */
    private Date analysisEnd;

    /**
     * 活动流程执行实例历史-目标客群客户ID列表
     */
    private String contactIds;

    /**
     * 活动流程执行实例历史-营销流程实例ID
     */
    private Integer marketingInstanceId;

    /**
     * 活动流程执行实例历史-营销流程定义ID
     */
    private Long marketingId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：活动流程执行实例历史-当前执行步骤
     *
     * @return 当前执行步骤
     */
    public Integer getStep() {
        return step;
    }

    /**
     * 设置：活动流程执行实例历史-当前执行步骤
     *
     * @param step 活动流程执行实例历史-当前执行步骤
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * 获取：活动流程执行实例历史-执行时间
     *
     * @return 执行时间
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * 设置：活动流程执行实例历史-执行时间
     *
     * @param executeTime 活动流程执行实例历史-执行时间
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * 获取：活动流程执行实例历史-结果名称
     *
     * @return 结果名称
     */
    public String getResult() {
        return result;
    }

    /**
     * 设置：活动流程执行实例历史-结果名称
     *
     * @param result 活动流程执行实例历史-结果名称
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * 获取：活动流程执行实例历史-订单分析起始
     *
     * @return 订单分析起始
     */
    public Date getAnalysisStart() {
        return analysisStart;
    }

    /**
     * 设置：活动流程执行实例历史-订单分析起始
     *
     * @param analysisStart 活动流程执行实例历史-订单分析起始
     */
    public void setAnalysisStart(Date analysisStart) {
        this.analysisStart = analysisStart;
    }

    /**
     * 获取：活动流程执行实例历史-订单分析结束
     *
     * @return 订单分析结束
     */
    public Date getAnalysisEnd() {
        return analysisEnd;
    }

    /**
     * 设置：活动流程执行实例历史-订单分析结束
     *
     * @param analysisEnd 活动流程执行实例历史-订单分析结束
     */
    public void setAnalysisEnd(Date analysisEnd) {
        this.analysisEnd = analysisEnd;
    }

    /**
     * 获取：活动流程执行实例历史-目标客群客户ID列表
     *
     * @return 目标客群客户ID列表
     */
    public String getContactIds() {
        return contactIds;
    }

    /**
     * 设置：活动流程执行实例历史-目标客群客户ID列表
     *
     * @param contactIds 活动流程执行实例历史-目标客群客户ID列表
     */
    public void setContactIds(String contactIds) {
        this.contactIds = contactIds == null ? null : contactIds.trim();
    }

    /**
     * 获取：活动流程执行实例历史-营销流程实例ID
     *
     * @return 营销流程实例ID
     */
    public Integer getMarketingInstanceId() {
        return marketingInstanceId;
    }

    /**
     * 设置：活动流程执行实例历史-营销流程实例ID
     *
     * @param marketingInstanceId 活动流程执行实例历史-营销流程实例ID
     */
    public void setMarketingInstanceId(Integer marketingInstanceId) {
        this.marketingInstanceId = marketingInstanceId;
    }

    /**
     * 获取：活动流程执行实例历史-营销流程定义ID
     *
     * @return 营销流程定义ID
     */
    public Long getMarketingId() {
        return marketingId;
    }

    /**
     * 设置：活动流程执行实例历史-营销流程定义ID
     *
     * @param marketingId 活动流程执行实例历史-营销流程定义ID
     */
    public void setMarketingId(Long marketingId) {
        this.marketingId = marketingId;
    }
}