package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 记录筛选节点的客群
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-07-25
 */
public class NodeFilterUserDO extends BaseModel implements Serializable {
    /**
     * 记录筛选节点的客群-node_id
     */
    private String nodeId;

    /**
     * 记录筛选节点的客群-node_type
     */
    private String nodeType;

    /**
     * 记录筛选节点的客群-node_name
     */
    private String nodeName;

    /**
     * 记录筛选节点的客群-marketing_id
     */
    private Long marketingId;

    /**
     * 记录筛选节点的客群-marketing_instance_id
     */
    private String marketingInstanceId;

    /**
     * 记录筛选节点的客群-customer_group_id
     */
    private Long customerGroupId;

    /**
     * 记录筛选节点的客群-open_id
     */
    private String openId;

    /**
     * 记录筛选节点的客群-phone
     */
    private String phone;

    /**
     * 记录筛选节点的客群-member_id
     */
    private Long memberId;

    /**
     * 记录筛选节点的客群-judge
     */
    private Short judge;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：记录筛选节点的客群-node_id
     *
     * @return node_id
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * 设置：记录筛选节点的客群-node_id
     *
     * @param nodeId
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * 获取：记录筛选节点的客群-node_type
     *
     * @return node_type
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * 设置：记录筛选节点的客群-node_type
     *
     * @param nodeType
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * 获取：记录筛选节点的客群-node_name
     *
     * @return node_name
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * 设置：记录筛选节点的客群-node_name
     *
     * @param nodeName
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * 获取：记录筛选节点的客群-marketing_id
     *
     * @return marketing_id
     */
    public Long getMarketingId() {
        return marketingId;
    }

    /**
     * 设置：记录筛选节点的客群-marketing_id
     *
     * @param marketingId
     */
    public void setMarketingId(Long marketingId) {
        this.marketingId = marketingId;
    }

    /**
     * 获取：记录筛选节点的客群-marketing_instance_id
     *
     * @return marketing_instance_id
     */
    public String getMarketingInstanceId() {
        return marketingInstanceId;
    }

    /**
     * 设置：记录筛选节点的客群-marketing_instance_id
     *
     * @param marketingInstanceId
     */
    public void setMarketingInstanceId(String marketingInstanceId) {
        this.marketingInstanceId = marketingInstanceId == null ? null : marketingInstanceId.trim();
    }

    /**
     * 获取：记录筛选节点的客群-customer_group_id
     *
     * @return customer_group_id
     */
    public Long getCustomerGroupId() {
        return customerGroupId;
    }

    /**
     * 设置：记录筛选节点的客群-customer_group_id
     *
     * @param customerGroupId
     */
    public void setCustomerGroupId(Long customerGroupId) {
        this.customerGroupId = customerGroupId;
    }

    /**
     * 获取：记录筛选节点的客群-open_id
     *
     * @return open_id
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * 设置：记录筛选节点的客群-open_id
     *
     * @param openId
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * 获取：记录筛选节点的客群-phone
     *
     * @return phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置：记录筛选节点的客群-phone
     *
     * @param phone
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取：记录筛选节点的客群-member_id
     *
     * @return member_id
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * 设置：记录筛选节点的客群-member_id
     *
     * @param memberId
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * 获取：记录筛选节点的客群-judge
     *
     * @return judge
     */
    public Short getJudge() {
        return judge;
    }

    /**
     * 设置：记录筛选节点的客群-judge
     *
     * @param judge
     */
    public void setJudge(Short judge) {
        this.judge = judge;
    }
}