package com.ztesoft.zsmart.nros.crm.core.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * 短信模板表
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-02
 */
public class SmsTemplateDO extends BaseModel implements Serializable {
    /**
     * 短信模板表-短信模板名称
     */
    private String templateName;

    /**
     * 短信模板表-短信模板内容
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：短信模板表-短信模板名称
     *
     * @return 短信模板名称
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * 设置：短信模板表-短信模板名称
     *
     * @param templateName 短信模板表-短信模板名称
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * 获取：短信模板表-短信模板内容
     *
     * @return 短信模板内容
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * 设置：短信模板表-短信模板内容
     *
     * @param templateContent 短信模板表-短信模板内容
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }
}