package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import lombok.Data;

import java.io.Serializable;

/**
 * @author bin.yu
 * @create 2019-06-10 16:10
 **/
@Data
public class AreaDTO implements Serializable {

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠
     */
    private Long areaId;

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-parent_id
     */
    private Long parentId;

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-area_name
     */
    private String areaName;

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-comments
     */
    private String comments;

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-area_code
     */
    private String areaCode;

    /**
     * 区域，网络服务区域，是一种逻辑的划分，通常和行政区域划分重叠SEQ: T_B-sp_id
     */
    private Integer spId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
