package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.alibaba.fastjson.JSONArray;
import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author yuanxiaokai
 * @date 2019/7/3
 */
@Data
public class CouponDTO extends BaseModel implements Serializable {
    /**
     * 优惠券-优惠券编码
     */
    private String couponCode;

    /**
     * 优惠券-优惠券名称
     */
    private String couponName;

    /**
     * 优惠券-优惠券类型:[1]满折券,[2]满减券,[3]满赠券,[4]满换券,[7]运费券
     */
    private String couponType;

    /**
     * 优惠券-优惠券详情
     */
    private String couponDetail;

    /**
     * 优惠券-是否限制发放数量:1:是 0 :否
     */
    private String isLimitQuantity;

    /**
     * 优惠券-总数量
     */
    private Integer quantity;

    /**
     * 优惠券-每人限领券数量
     */
    private Integer getLimit;

    /**
     * 优惠券-优惠券状态:[0]设计中,[1]启用,[2]作废
     */
    private String couponStatus;

    /**
     * 优惠券-是否支持全部门店:1:是 0 :否
     */
    private String useAllLocations;

    /**
     * 优惠券-发券门店组ID集合
     */
    private JSONArray storeCode;

    /**
     * 优惠券-开始领取时间
     */
    private Date startTime;

    /**
     * 优惠券-有效期类型:[1]指定日期截止,[2]指定领取后有效天数
     */
    private String validTimeType;

    /**
     * 优惠券-领取截止时间
     */
    private Date receiveEndTime;

    /**
     * 优惠券-有效期截止时间
     */
    private Date useEndTime;

    /**
     * 优惠券-领取后多少天内有效
     */
    private Integer fixedTerm;

    /**
     * 优惠券-优惠券渠道类型
     */
    private JSONArray channel;

    /**
     * 优惠券-商品范围类型：[0]全部商品,[1]品类,[2]品牌
     */
    private String goodsRangeLimitType;

    /**
     * 优惠券-备注信息
     */
    private String couponRemark;

    /**
     * 优惠券-卡券失效原因
     */
    private String invalidRemark;

    /**
     * 优惠券-规则ID
     */
    private Long ruleId;

    /**
     * 规则名称
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 规则DTO
     */
    private RuleDTO ruleDTO;

    /**
     * 优惠券商品范围列表
     */
    private List<CouponGoodsRangeDTO> couponGoodsRangeList;

    /**
     * 已领取数量
     */
    private Long receivedNumber;

    /**
     * 未领取数量
     */
    private Long unreceivedNumber;

    /**
     * 已核销取数量
     */
    private Long usedNumber;

    /**
     * 未核销数量
     */
    private Long unusedNumber;
}

