package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.alibaba.fastjson.JSONArray;
import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 优惠券实例DTO
 * @author wangzhe
 * @date 2019-04-09
 */
@Data
public class CouponInstanceDTO extends BaseModel implements Serializable {

    /**
     * 优惠券-优惠券编码
     */
    private String couponCode;

    /**
     * 优惠券-优惠券名称
     */
    private String couponName;

    /**
     * 优惠券-卡券类型
     */
    private String couponType;

    /**
     * 优惠券-是否支持全部门店:1:是 0 :否
     */
    private String useAllLocations;

    /**
     * 优惠券-发券门店集合
     */
    private JSONArray storeCode;

    /**
     * 优惠券-优惠券渠道类型
     */
    private JSONArray channel;

    /**
     * 优惠券-商品范围类型,[1]商品,[2]品类,[3]品牌
     */
    private String goodsRangeLimitType;

    /**
     * 优惠券商品范围列表
     */
    private List<CouponGoodsRangeDTO> couponGoodsRangeList;

    /**
     * 优惠券-优惠详情
     */
    private String couponDetail;

    /**
     * 优惠券领取记录-发放人名称
     */
    private String sendUserName;

    /**
     * 优惠券领取记录-领取人名称
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 卡券类型名称
     */
    private String couponTypeName;

    /**
     * 优惠券实例编码
     **/
    private String instanceCode;

    /**
     * 是否锁定
     **/
    private String isLock;

    /**
     * 是否核销
     **/
    private String isUse;

    /**
     * 接收时间
     **/
    private Date receiveTime;

    /**
     * 规则ID
     */
    private Long ruleId;

    /**
     * 规则DTO
     */
    private RuleDTO ruleDTO;

    /**
     * 有效期开始时间
     */
    private Date useStartTime;

    /**
     * 有效期结束时间
     */
    private Date useEndTime;

    /**
     * 核销时间
     */
    private Date useTime;

    /**
     * 优惠券领取记录-领取方式:[0]会员营销活动,[1]促销活动,[2]自领,[3]其他
     */
    private String receiveType;

    /**
     * 优惠券领取记录-领取渠道
     */
    private String receiveChannel;

    /**
     * 优惠券领取记录-领券活动ID
     */
    private Long promotionId;

    /**
     * 优惠券领取记录-订单编码
     */
    private String orderCode;

    /**
     * 优惠券领取记录-自助核销时所需验证码
     */
    private String verifyCode;

    /**
     * 领取门店ID
     */
    private Long storeId;

    /**
     * 领取门店名称
     */
    private String storeName;

    /**
     * 优惠券实例状态 0:可使用  1:失效  2:已核销  3:已冻结
     */
    private String instanceStatus;

}