package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 活动优惠
 * @author   wangzhe
 * @date     2019/6/2 23:58
 */
@Data
public class DiscountDTO extends BaseModel implements Serializable {
    /**
     * 活动优惠-优惠名称
     */
    private String discountName;

    /**
     * 活动优惠-折扣（%）
     */
    private BigDecimal discount;

    /**
     * 活动优惠-立减
     */
    private Long reducePrice;

    /**
     * 活动优惠-特价
     */
    private Long bargainPrice;

    /**
     * 活动优惠-免费数量
     */
    private Integer freeQuantity;

    /**
     * 活动优惠-赠送数量
     */
    private Integer giftQuantity;

    /**
     * 活动优惠-是否免运费:[0]否,[1]是
     */
    private String freeFreight;

    /**
     * 活动优惠-成本分担模式:[1]进价差,[2]售价差,[3]新扣率,[4]保毛利率,[5]固定金额
     */
    private String costSharingMode;

    /**
     * 活动优惠-成本分担值（%）
     */
    private BigDecimal costSharingValue;

    /**
     * 活动优惠-条件ID
     */
    private Long conditionId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}