package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;

/**
 * Created with IntelliJ IDEA.
 * Description:
 * User: yaodingw
 * Date: 2019-04-17
 * Time: 11:08
 */
@Data
public class EnumConfigDTO extends BaseModel implements Serializable {

    /**
     * EnumConfigDO-field_code
     */
    private String fieldCode;

    /**
     * EnumConfigDO-field_name
     */
    private String fieldName;

    /**
     * EnumConfigDO-table_code
     */
    private String tableCode;

    /**
     * EnumConfigDO-table_name
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
