package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;

/**
 * 返券
 * @author   wangzhe
 * @date     2019/6/2 23:59
 */
@Data
public class GiftCouponDTO extends BaseModel implements Serializable {
    /**
     * 返券-优惠券编码
     */
    private String couponCode;

    /**
     * 返券-优惠券名称
     */
    private String batchName;

    /**
     * 返券-数量
     */
    private Integer quantity;

    /**
     * 返券-条件ID
     */
    private Long conditionId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}