package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 赠品
 * @author   wangzhe
 * @date     2019/6/2 23:59
 */
@Data
public class GiftDTO extends BaseModel implements Serializable {
    /**
     * 赠品-赠品SKU
     */
    private String skuCode;

    /**
     * 赠品-赠品名称
     */
    private String name;

    /**
     * 赠品-赠品数量
     */
    private Integer quantity;

    /**
     * 赠品-成本分担模式:[1]进价差,[2]售价差,[3]新扣率,[4]保毛利率,[5]固定金额
     */
    private String costSharingMode;

    /**
     * 赠品-成本分担值（%）
     */
    private BigDecimal costSharingValue;

    /**
     * 赠品-条件ID
     */
    private Long conditionId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}