package com.ztesoft.zsmart.nros.crm.core.server.middleware.rpc.feigin.proxy.model;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 加价换购
 * @author   wangzhe
 * @date     2019/6/2 23:59
 */
@Data
public class PurchaseDTO extends BaseModel implements Serializable {
    /**
     * 加价换购-换购商品SKU
     */
    private String skuCode;

    /**
     * 加价换购-换购商品名称
     */
    private String name;

    /**
     * 加价换购-换购商品价格
     */
    private Long price;

    /**
     * 加价换购-成本分担模式:[1]进价差,[2]售价差,[3]新扣率,[4]保毛利率,[5]固定金额
     */
    private String costSharingMode;

    /**
     * 加价换购-成本分担值（%）
     */
    private BigDecimal costSharingValue;

    /**
     * 加价换购-订单限购数量
     */
    private Integer orderQuantityLimit;

    /**
     * 加价换购-条件ID
     */
    private Long conditionId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}