package com.ztesoft.zsmart.nros.crm.core.server.domain.marketing.model;

import java.io.Serializable;

import com.ztesoft.zsmart.nros.common.model.BaseModel;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 营销流程节点执行记录
 * 
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-07-24
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class NodeExecuteRecordBO extends BaseModel implements Serializable {
    /**
     * 活动节点执行记录-node_type
     */
    private String nodeType;

    /**
     * 活动节点执行记录-node_id
     */
    private String nodeId;

    /**
     * 活动节点执行记录-node_name
     */
    private String nodeName;

    /**
     * 活动节点执行记录-marketing_id
     */
    private Long marketingId;

    /**
     * 活动节点执行记录-marketing_instance_id
     */
    private String marketingInstanceId;

    /**
     * 活动节点执行记录-param
     */
    private String param;

    /**
     * 活动节点执行记录-result
     */
    private String result;

    /**
     * 活动节点执行记录-target_user_count
     */
    private Long targetUserCount;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}